// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cedulas.proto

package com.cedulasservicegrpc.grpc;

public interface CedulasResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CedulasResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string cedulas = 1;</code>
   */
  java.util.List<java.lang.String>
      getCedulasList();
  /**
   * <code>repeated string cedulas = 1;</code>
   */
  int getCedulasCount();
  /**
   * <code>repeated string cedulas = 1;</code>
   */
  java.lang.String getCedulas(int index);
  /**
   * <code>repeated string cedulas = 1;</code>
   */
  com.google.protobuf.ByteString
      getCedulasBytes(int index);
}
