// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cedulas.proto

package com.cedulasservicegrpc.grpc;

public interface CedulasRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CedulasRequest)
    com.google.protobuf.MessageOrBuilder {
}
